# Generated by Django 4.2.7 on 2025-11-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(max_length=255)),
                ('siege_agence', models.TextField()),
                ('num_contact', models.CharField(max_length=20)),
                ('email_agence', models.EmailField(max_length=254, unique=True)),
                ('nmbr_succursales', models.PositiveIntegerField(default=0)),
                ('nmbr_flotte', models.PositiveIntegerField(default=0)),
                ('logo_agence', models.ImageField(blank=True, null=True, upload_to='agencies/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'db_table': 'agences',
            },
        ),
        migrations.CreateModel(
            name='DemandePartenariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prop', models.CharField(max_length=255)),
                ('prenom_prop', models.CharField(max_length=255)),
                ('ddn_prop', models.DateField()),
                ('email_prop', models.EmailField(max_length=254)),
                ('phone_prop', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('nom_agence', models.CharField(max_length=255)),
                ('siege_agence', models.TextField()),
                ('logo_agence', models.ImageField(blank=True, null=True, upload_to='partnerships/logos/')),
                ('num_contact', models.CharField(max_length=20)),
                ('email_agence', models.EmailField(max_length=254)),
                ('nmbr_succursales', models.PositiveIntegerField(default=0)),
                ('nmbr_flotte', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.administrateur')),
            ],
            options={
                'verbose_name': 'Demande Partenariat',
                'verbose_name_plural': 'Demandes Partenariat',
                'db_table': 'demandes_partenariat',
            },
        ),
        migrations.CreateModel(
            name='DemandeCompteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=255)),
                ('prenom_admin', models.CharField(max_length=255)),
                ('ddn_admin', models.DateField()),
                ('email_admin', models.EmailField(max_length=254)),
                ('phone_admin', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_admin', to='agencies.agence')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_admin', to='accounts.proprietaireagence')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.administrateur')),
            ],
            options={
                'verbose_name': 'Demande Compte Admin',
                'verbose_name_plural': 'Demandes Compte Admin',
                'db_table': 'demandes_compte_admin',
            },
        ),
    ]
