# Generated by Django 4.2.7 on 2025-11-14 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agencies', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaireagence',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretaires', to='agencies.agence'),
        ),
        migrations.AddField(
            model_name='secretaireagence',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretaire_agence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proprietaireagence',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietaires', to='agencies.agence'),
        ),
        migrations.AddField(
            model_name='proprietaireagence',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire_agence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locataire',
            name='banned_from_agencies',
            field=models.ManyToManyField(blank=True, related_name='banned_locataires', to='agencies.agence'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locataire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garagiste',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garagistes', to='agencies.agence'),
        ),
        migrations.AddField(
            model_name='garagiste',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garagiste', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminagence',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins_agence', to='agencies.agence'),
        ),
        migrations.AddField(
            model_name='adminagence',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_agence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
