# Generated by Django 4.2.7 on 2025-11-14 21:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_dpt', models.TextField()),
                ('capacite_dpt', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='agencies.agence')),
            ],
            options={
                'verbose_name': 'Dépôt',
                'verbose_name_plural': 'Dépôts',
                'db_table': 'depots',
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('marque', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('prix_heure', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('etat_vehicule', models.CharField(choices=[('intrusion', 'Intrusion'), ('enPanne', 'En Panne'), ('prochainementDisponible', 'Prochainement Disponible'), ('enMarche', 'En Marche'), ('enArret', 'En Arrêt')], default='enMarche', max_length=50)),
                ('disponibilite', models.BooleanField(default=True)),
                ('categorie_vehicule', models.CharField(choices=[('Petites', 'Petites'), ('Moyennes', 'Moyennes'), ('Larges', 'Larges'), ('Premium', 'Premium'), ('Monospaces', 'Monospaces'), ('SUV', 'SUV')], max_length=50)),
                ('img_vhl', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='agencies.agence')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicules', to='vehicles.depot')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'db_table': 'vehicules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrixHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nouveau_prix_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancien_prix_heure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nouveau_prix_heure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_history', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'Prix Historique',
                'verbose_name_plural': 'Prix Historiques',
                'db_table': 'prix_historique',
                'ordering': ['-created_at'],
            },
        ),
    ]
