# Generated by Django 4.2.7 on 2025-11-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_SIGNATURE', 'En attente de signature'), ('SIGNED', 'Signé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_locataire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Contrat Location',
                'verbose_name_plural': 'Contrats Location',
                'db_table': 'contrats_location',
            },
        ),
    ]
