# Generated by Django 4.2.7 on 2025-11-14 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('accounts', '0001_initial'),
        ('agencies', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_reclamation', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolue'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20)),
                ('traite_at', models.DateTimeField(blank=True, null=True)),
                ('reponse', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='agencies.agence')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='accounts.locataire')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='reservations.reservation')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to='accounts.proprietaireagence')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'db_table': 'reclamations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type_rapport', models.CharField(choices=[('ACCIDENT', 'Accident'), ('PANNE', 'Panne'), ('AUTRE', 'Autre problème')], default='AUTRE', max_length=20)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='agencies.agence')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='accounts.locataire')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='reservations.reservation')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtatVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_general', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('BON', 'Bon'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais'), ('CRITIQUE', 'Critique')], max_length=20)),
                ('description', models.TextField()),
                ('kilometrage', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garagiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_vehicules', to='accounts.garagiste')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'État Véhicule',
                'verbose_name_plural': 'États Véhicule',
                'db_table': 'etats_vehicule',
                'ordering': ['-created_at'],
            },
        ),
    ]
